version: "3"
services:
  app:
    build:
        dockerfile: Dockerfile
        context: ./website-amenities
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      amenities-app:
          ipv4_address: "172.20.0.4"
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      amenities-app:
        ipv4_address: "172.20.0.3"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      amenities-app:
        ipv4_address: "172.20.0.2"
networks:
    amenities-app:
      ipam:
        config:
          - subnet: "172.20.0.0/16"
      driver: bridge
