version: "2"
services:
  app:
    build:
        dockerfile: Dockerfile
        context: ./website-amenities
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "5000:5000"
networks:
    default:
        external:
          name: cs329s-project_default